version: '3.1'
services:
  zeus-server-service-admin-provider:
    image: 49.233.78.39:5000/zeus-server-service-admin-provider:v1.0.0
    container_name: zeus-server-service-admin-provider
    ports:
    - 7209:7209  #http
    - 22991:22991 #dubbo
    environment:
      TZ: Asia/Shanghai
networks:
  default:
    external:
      name: zeus  #net
