version: '3.1'
services:
  zeus-service-sso:
    image: 49.233.78.39:5000/zeus-service-sso:v1.0.0
    container_name: zeus-service-sso
    ports:
    - 7210:7210  #http
    - 22992:22992  #运维
    environment:
      TZ: Asia/Shanghai

networks:
  default:
    external:
      name: zeus  #net
