version: '3.1'
services:
  mars-server-service-admin-consumer:
    image: ip:5000/mars-server-service-admin-consumer:v1.0.0
    container_name: mars-server-service-admin-consumer
    ports:
    - 8205:8205  #http
    - 22881:22881
    environment:
      TZ: Asia/Shanghai
networks:
  default:
    external:
      name: mars  #net