version: '3.1'
services:
  mars-server-service-admin-provider:
    image: 118.31.122.157:5000/mars-server-service-admin-provider:v1.0.0
    container_name: mars-server-service-admin-provider
    ports:
    - 8209:8209  #http
    - 22889:22889
    environment:
      TZ: Asia/Shanghai
networks:
  default:
    external:
      name: mars  #net