version: '3.1'
services:
  mars-server-service-order-provider:
    image: ip:5000/mars-server-service-order-provider:v1.0.0
    container_name: mars-server-service-order-provider
    ports:
    - 8303:8303  #http
    - 23883:23883
    environment:
      TZ: Asia/Shanghai
networks:
  default:
    external:
      name: mars  #net