version: '3.1'
services:
  mars-server-service-order-consumer:
    image: 118.31.122.157:5000/mars-server-service-order-consumer:v1.0.0
    container_name: mars-server-service-order-consumer
    ports:
    - 8304:8304  #http
    - 23884:23884
    environment:
      TZ: Asia/Shanghai
networks:
  default:
    external:
      name: mars  #net
