version: '3.1'
services:
  mars-service-redis-provider:
    image: ip:5000/mars-service-redis-provider:v1.0.0
    container_name: mars-service-redis-provider
    ports:
    - 9901:9901
    - 30881:30881
    environment:
      TZ: Asia/Shanghai      

networks:
  default:
    external:
      name: mars  #net
      