version: '3.1'
services:
  mars-server-service-shop-consumer:
    image: ip:5000/mars-server-service-shop-consumer:v1.0.0
    container_name: mars-server-service-shop-consumer
    ports:
    - 8302:8302  #http
    - 23882:23882
    environment:
      TZ: Asia/Shanghai
networks:
  default:
    external:
      name: mars  #net