version: '3.1'
services:
  mars-server-service-user-provider:
    image: 118.31.122.157:5000/mars-server-service-user-provider:v1.0.0
    container_name: mars-server-service-user-provider
    ports:
    - 8104:8104  #http
    - 21884:21884
    environment:
      TZ: Asia/Shanghai
networks:
  default:
    external:
      name: mars  #net